### ISSUE TITLE
After double click zoom map may not contain area that was clicked

### ISSUE THREAD

**Issue by tylere** [ellisonbg/ipyleaflet#130]
When zooming by using a double click, the center of the map stays constant, rather than panning to include the area where the user double clicked. This seems non-intuitive, and is in contrast to the default Leaflet behavior (as demonstrated on the [Leaflet website](http://leafletjs.com/)), which pans the map to include the area where the user has double clicked.

**Comment by Juanlu001** [comment]
I just found the same thing:

![ezgif com-optimize 4](https://user-images.githubusercontent.com/316517/37649763-21a60e22-2c33-11e8-864d-be097691b4d2.gif)

**Comment by Juanlu001** [comment]
At first, I thought that the "default" behavior could be achieved setting `doubleClickZoom` to `center`, as the documentation says:

> Whether the map can be zoomed in by double clicking on it and zoomed out by double clicking while holding shift. If passed 'center', double-click zoom will zoom to the center of the  view regardless of where the mouse was.

But in ipyleaflet it's defined as a boolean:

https://github.com/ellisonbg/ipyleaflet/blob/ae24dd6c17cef8c2e9d2f50b4cd64deffb8d12ee/ipyleaflet/leaflet.py#L628

So I went ahead and changed it to be a `double_click_zoom = Union([Bool(True), Unicode('center')]).tag(sync=True, o=True)`. However, this is not a solution either, since then it just ignores the position of the mouse. Just leaving this here so nobody else loses time trying to find a workaround.

**Comment by SylvainCorlay** [comment]
@Juanlu001 @tylere Thanks for the report. I have opened PR #132 to fix this issue.

Would you be ok with trying this out?

There are very subtle race condition with respect to how leaflet.js handles its internal state and I would like to be sure that there is no unwanted side effect here.
